### ISSUE TITLE
Accessibility - check accessibility tree of all components

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/boiler#376]
#### Description / User Story

The goal of this ticket is to check the accessibility tree of all components either manually or automatically and document the findings. This is a prerequisite for follow up tasks, that deal with fixing all the issues that were found.

----
#### Requirements
- [ ] #452 
- [x] #552 

----
#### Acceptance Criteria
- [ ] Accessibility tree was checked for all components and findings (issues that need to be fixed) were documented:
   - [ ] IconButton
   - [ ] Divider
   - [ ] FormCaptionGroup
   - [ ] Icon
   - [ ] ButtonGroup
   - [ ] Tooltip
   - [ ] FormCaption
   - [ ] Tooltip -> TooltipBubble
   - [ ] TextButton
   - [ ] Loader
   - [ ] Counter
   - [ ] FormLabel
   - [ ] TextArea
   - [ ] TextInput
   - [ ] RadioGroup
   - [ ] Select
   - [ ] Checkbox
   - [ ] RadioGroup -> Radio
   - [ ] ToggleSwitch
   - [ ] NumberInput
   - [ ] If #462 is done: Stepper Button / Combo
   - [ ] If #567 is done: Input Icon
   - [ ] Tab
   - [ ] TabBar
   - [ ] If #268 is done: SliderSingleValue
   - [ ] If #268 is done: SliderTwoValues

----
#### Background information
- Lars T. raised a question in #2 that we may have should look into again: 
   > Can we provide accessible components without Typescript that enforces/forbids the use of cetrain props?
   > Maybe we can only offer AA standard when the team also uses the Types for our components.

**Comment by thrbnhrtmnn** [comment]
It was decided to split this issue, the first one being #1020 with follow up tasks being created afterwards
