### ISSUE TITLE
Input Field Number - fix input background, value and unit color

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#933]
### Description / User story

In design the input field of the Input Field Number has a non-transparent background color. In code the color is transparent and should be changed to the correct color, defined by design.

~Furthermore the unit color is different when the value is empty and when the value is filled in design, but in code it is always the same. The unit color for when the value is empty needs to be added in code.~ It should be the same, as it now is also in design.

Another missing color when comparing design and code is the unit, placeholder and value in the error state. According to design the value color is a dark red in the error state, in code the color is the same as in other states (dark-grey/black/white).

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] The background color of the input field in the Input Field Number in code is the same as in design in light and dark mode (also in regards to transparency)
- [x] The stepper icon color of the input field in the Input Field Number in code is the same as in design in light and dark mode in disabled and readonly state (also in regards to transparency)
- [x] The color of the value in the Input Field Number in code is the same as in design in error state. (might also be fixed with #683, in case we are already using the right token)
- [ ] The color of the unit in the Input Field Number in code is the same as in design in error state. (might also be fixed with #683, in case we are already using the right token)
- [x] The color of the placeholder in the Input Field Number in code is the same as in design in error state. (might also be fixed with #683, in case we are already using the right token)

### Additional information

- A related task is #831 , where the properties "unit" and "prependUnit" / "hasUnit" are renamed/changed.
- Font color of error state is also part of #683 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
